from selenium import webdriver
from selenium.webdriver import ActionChains
from webdriver_manager.chrome import ChromeDriverManager
from time import sleep
driver=webdriver.Chrome(ChromeDriverManager().install())


#subpals activation

driver.get("https://www.subpals.com/login/final/UC4oGmZwHNT5gbasx6AZHviA/")
sleep(2)
driver.find_element_by_name("password").send_keys("Your Password")
sleep(2)
driver.find_element_by_name("password").send_keys("\ue007")
sleep(2)
driver.find_element_by_name("starter").submit()
sleep(2)
driver.get("https://www.subpals.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.subpals.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.subpals.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.subpals.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.subpals.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.subpals.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.subpals.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.subpals.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.subpals.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.subpals.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.subpals.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.subpals.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.subpals.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.subpals.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.subpals.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.subpals.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.subpals.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.subpals.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.subpals.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.subpals.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.subpals.com/members-area/activate/")
sleep(2)


#ytpals activation


driver.get("https://www.ytpals.com/login/final/UC4oGmZwHNT5gbasx6AZHviA/")
sleep(2)
driver.find_element_by_name("password").send_keys("Your Password")
sleep(2)
driver.find_element_by_name("password").send_keys("\ue007")
sleep(2)
driver.find_element_by_name("starter").submit()
sleep(2)
driver.get("https://www.ytpals.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.ytpals.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.ytpals.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.ytpals.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.ytpals.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.ytpals.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.ytpals.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.ytpals.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.ytpals.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.ytpals.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.ytpals.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.ytpals.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.ytpals.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.ytpals.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.ytpals.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.ytpals.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.ytpals.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.ytpals.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.ytpals.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.ytpals.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.ytpals.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.ytpals.com/members-area/activate/")
sleep(2)


#sonuker activation


driver.get("https://www.sonuker.com/login/final/UC4oGmZwHNT5gbasx6AZHviA/")
sleep(2)
driver.find_element_by_name("password").send_keys("Your Password")
sleep(2)
driver.find_element_by_name("password").send_keys("\ue007")
sleep(2)
driver.find_element_by_name("starter").submit()
sleep(2)
driver.get("https://www.sonuker.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.sonuker.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.sonuker.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.sonuker.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.sonuker.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.sonuker.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.sonuker.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.sonuker.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.sonuker.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.sonuker.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.sonuker.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.sonuker.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.sonuker.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.sonuker.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.sonuker.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.sonuker.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.sonuker.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.sonuker.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.sonuker.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.sonuker.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.sonuker.com/members-area/sub-completed-v4.php")
sleep(2)
driver.get("https://www.sonuker.com/members-area/activate/")
sleep(2)
